### ISSUE TITLE
[BUG] MCRPG - Cooldown and ability

### ISSUE THREAD

**Issue by TheBlothHoondr** [playoutpost/issue-tracker#18]
Encounter a bug with the MCRPG plugins where i just passed level 200 on mining and unlocked orescanner which i put it instead of superbreaker (replaced by ore scanner), i start using it (it's working) but suddenly stopped working and since still don't work, i mean by that i can't raise my pickaxe to use the ability of orescanner and i can't change orescanner to superbreaker because of a cooldown glitched (i need to stay online 16 hours without disconnecting to be able to change the abilities, cooldown stop counting when offline). my abilities are all on and i'm capable of raising my sword

**To Reproduce**
Steps to reproduce the bug
1.Have Orescanner unlocked
2. Press right click to activate Orescanner
3. Seeing not working._

**Screenshots**
![2020-01-16_13 09 32](https://user-images.githubusercontent.com/59937562/72524837-0e3cba00-3863-11ea-8303-13e5905d8d65.png)
![2020-01-16_13 15 20](https://user-images.githubusercontent.com/59937562/72524839-0e3cba00-3863-11ea-95c6-92de64d3d433.png)
![2020-01-16_13 09 15](https://user-images.githubusercontent.com/59937562/72524840-0ed55080-3863-11ea-93b2-bde819fb8709.png)
![2020-01-16_13 09 27](https://user-images.githubusercontent.com/59937562/72524842-0ed55080-3863-11ea-8162-6deb400b41be.png)

**Screenshots**

**Comment by thecenters** [comment]
I've passed this information to the developer of the plugin

**Comment by DiamondDagger590** [comment]
Working on rewriting the Cooldown system of the replace to be in game time and not playtime, unsure why I did it that way in the first place.

Working on a fix for the Ore Scanner issue currently. Hopefully will have a fix sometime tonight

**Comment by DiamondDagger590** [comment]
Fix is sent to Centers, just waiting on him to find a good time to put it up
